name: Deploy Shopify Theme

on:
  push:
    branches: [ "staging", "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      SHOPIFY_FLAG_TTY: 0
      SHOPIFY_SHOP: neofollics-dev.myshopify.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tools
        run: |
          npm ci || npm i
          npm run lint
          npm run build

      # Swap environment settings (optional)
      - name: Use env settings
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            cp config/settings_data.live.json config/settings_data.json
          else
            cp config/settings_data.staging.json config/settings_data.json
          fi
        shell: bash

      - name: Install Shopify CLI
        run: npm i -g @shopify/cli @shopify/theme

      - name: Push to theme
        env:
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
          LIVE_THEME_ID: ${{ secrets.LIVE_THEME_ID }}
          STAGING_THEME_ID: ${{ secrets.STAGING_THEME_ID }}
        run: |
          THEME_ID=$STAGING_THEME_ID
          if [ "${{ github.ref_name }}" = "main" ]; then
            THEME_ID=$LIVE_THEME_ID
          fi

          # Push only changed files, keep editor-safe
          npx shopify theme push \
            --store "$SHOPIFY_SHOP" \
            --theme "$THEME_ID" \
            --only-changed \
            --json
